routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('/homes', function () {
//     return view('welcome');
// });

Route::resource('Event', 'EventController');
Route::resource('Kategori', 'KategoriController');
Route::resource('Komentar', 'KomentarController');
Route::resource('Lokasi', 'LokasiController');
Route::resource('Organizer', 'OrganizerController');
Route::resource('Profile', 'ProfileController');

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

app/Komentar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Komentar extends Model
{
    //
    public $timestamps = false;
    protected $table = "Komentar";
    protected $fillable = ["user_id", "event_id","komentar"];

    public function event()
    {
        return $this->belongsTo('App\Event');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/KomentarController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\Komentar;
use Illuminate\Http\Request;
use Auth;

use DB;
use Redirect;
class KomentarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $komentar = Komentar::all();
        
        $iduser= Auth::user()->id;  
        // dd($idprof);
        $idprof= Profile::select('id')->where("user_id",$iduser)->value('id');
        $idorg = Organizer::where('profile_id',$idprof)->first();
        $lokasi= DB::table('lokasi')->get();
        // dd($idorg);
    
        $kategori = DB::table('kategori')->get();
        // $event = Event::where('profile_id')
        
        
        return view('event.create',compact("lokasi","idorg","kategori"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
    		'komentar' => 'required',
    		'event_id' => 'required',
            'user_id' =>  'required',
            
    	]);
        $event_id = $request->event_id;
        $iduser= Auth::user()->id;
        Komentar::create([
    		'komentar' => $request->komentar,
    		'event_id' => $request->event_id,
            'user_id' => $iduser,
            
    	]);
        
    	return redirect()->route('Event.show', ['Event' => $event_id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $komentar = Komentar::findorfail($id);
        $komentar->delete();
        $idevent= $komentar->value('event_id');
        
        return redirect()->route('Event.show', ['Event' => $idevent]);
    }
}

resources/views/komentar/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Add Event</title>

    <!-- Icons font CSS-->
    <link href="{{asset('colorlib/vendor/mdi-font/css/material-design-iconic-font.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('colorlib/vendor/font-awesome-4.7/css/font-awesome.min.css')}}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{{asset('colorlib/vendor/select2/select2.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('colorlib/vendor/datepicker/daterangepicker.css')}}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{{asset('colorlib/css/main.css')}}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">Comment Form</h2>
                    <form method="POST" action="{{ route('Komentar.store') }}" enctype="multipart/form-data">
                        @csrf
                        
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Nama</label>
                                    <input class="input--style-4" readonly="readonly" value="{{Auth::user()->nama}}" type="text" >
                                </div>
                            </div>
                            @error('nama')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Komentar</label>
                                    <input class="input--style-4" type="text" name="komentar" >
                                </div>
                            </div>
                        </div>
                            @error('waktu')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror

                            <input class="input--style-4" readonly="readonly" value="{{Auth::user()->id}}" type="text" name="nama">
                            
                          
                        
                        <br>
                        <div class="p-t-15">
                            <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
        
    <!-- Jquery JS-->
    <script src="{{asset('colorlib/vendor/jquery/jquery.min.js')}}"></script> 
    <script src="{{asset('colorlib/vendor/jquery/jquery.min.js')}}"></script>
    <!-- Vendor JS-->
    <script src="{{asset('colorlib/vendor/select2/select2.min.js')}}"></script>
    <script src="{{asset('colorlib/vendor/datepicker/moment.min.js')}}"></script>
    <script src="{{asset('colorlib/vendor/datepicker/daterangepicker.js')}}"></script>

    <!-- Main JS-->
    <script src="{{asset('colorlib/js/global.js')}}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

resources/views/komentar/show.blade.php
@extends('listco.master')

@section('content')
<!--? Hero Start -->
<div class="slider-area2">
         <div class="slider-height3  hero-overly hero-bg4 d-flex align-items-center">
               <div class="container">
                  <div class="row">
                     <div class="col-xl-12">
                           <div class="hero-cap2 pt-20 text-center">
                              <h2>Komentar</h2>
                           </div>
                     </div>
                  </div>
               </div>
         </div>
      </div>
      <!-- Hero End -->
<!--? Blog Area Start -->
<
                  
                  <div class="comments-area">
                     <div class="form-group">
                        <a class="btn btn-primary" href="{{ route('Komentar.index') }}" role="button">Go Back</a>
                     </div> 
                     @forelse($user as $key=>$val)
                     
                     <p>{{$val->nama}}</p>
                        @foreach($val->komentar as $item)
                           <div class="comment-list">
                              <div class="single-comment justify-content-between d-flex">
                                 <div class="user justify-content-between d-flex">
                                    <div class="thumb">
                                       <img src="{{('listco/assets/img/blog/comment_1.png')}}" alt="">
                                    </div>
                                    <div class="desc">
                                       <!-- <h3 class="text-left my-3">Comments:</h3> -->
                                       
                                       <p class="comment"> 
                                          {{$item->komentar}}  <br>
                                                                                 
                                       </p>
                                       <div class="d-flex justify-content-between">
                                          <div class="d-flex align-items-center">
                                             <h5>
                                                <a href="#">Emily</a>
                                             </h5>                                             
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        @endforeach                           
                        @empty
                        <h2 class="text-center">No one comment</h2>
                     @endforelse
                  </div>
                  @auth
                  <div class="comment-form">
                     <h4>Leave a Reply</h4>
                     <form class="form-contact comment_form" method="post" action="{{ route('Komentar.store') }}" id="commentForm">
                        @csrf
                        <div class="row">
                           <div class="col-12">
                              <div class="form-group">
                                 <textarea class="form-control w-100" name="komentar" id="comment" cols="30" rows="9"
                                    placeholder="Write Comment"></textarea>
                              </div>
                           </div>
                           <div class="col-sm-3">
                              <div class="form-group">
                                 <input class="form-control" name="user_id" id="name" type="text" readonly='readonly' value="{{Auth::user()->name}}" placeholder="Name">
                              </div>
                              <div class="form-group">
                                 <input class="form-control" name="event_id" id="name" type="hidden" readonly='readonly' value="{{$event->id}}" placeholder="Name">
                              </div>
                              
                           </div>
                           
                           
                        </div>
                        <div class="form-group">
                           <button type="submit" class="button button-contactForm btn_1 boxed-btn">Post Comment</button>
                        </div>
                     </form>
                  </div>
                  @endauth
                  @guest
                  <h2 class="text-center">Please login to comment</h2>
                  @endguest
               </div>
               
            </div>
         </div>
      </section>
@endsection