routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('/homes', function () {
//     return view('welcome');
// });

Route::resource('Event', 'EventController');
Route::resource('Kategori', 'KategoriController');
Route::resource('Komentar', 'KomentarController');
Route::resource('Lokasi', 'LokasiController');
Route::resource('Organizer', 'OrganizerController');
Route::resource('Profile', 'ProfileController');

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    //
    public $timestamps = false;
    protected $table = "event";
    protected $fillable = ["nama", "waktu","kategori_id","organizer_id","lokasi","lokasi_id",'harga','deskripsi'];

    public function lokasi()
    {
        return $this->belongsTo('App\Lokasi');
    }
    public function organizer()
    {
        return $this->belongsTo('App\Organizer');
    }
    public function komentar()
    {
        return $this->hasMany('App\Komentar');
    }
    public function kategori()
    {
        return $this->belongsTo('App\Kategori');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Event;
use App\Kategori;
use App\Komentar;
use App\Organizer;
use App\Profile;
use App\Lokasi;
use App\User;
use Auth;
use DB;
class EventController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except('index','show');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $event = Event::all();
        $lokasi = Lokasi::all();

        return view('event.index', compact('event','lokasi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $iduser= Auth::user()->id;
        // dd($idprof);
        $idprof= Profile::select('id')->where("user_id",$iduser)->value('id');
        $idorg = Organizer::where('profile_id',$idprof)->first();
        $lokasi= DB::table('lokasi')->get();
        // dd($idorg);
    
        $kategori = DB::table('kategori')->get();
        
        
        return view('event.create',compact("lokasi","idorg","kategori"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
    		'nama' => 'required',
    		'waktu' => 'required',
            'lokasi' =>  'required',
            'kategori_id' => 'required',
            'lokasi_id' => 'required',
            'organizer_id' => 'required',
            'harga' => 'required',
            'deskripsi' => 'required',
    	]);
 
        Event::create([
    		'nama' => $request->nama,
    		'waktu' => $request->waktu,
            'lokasi' => $request->lokasi,
            'kategori_id' => $request->kategori_id,
            'lokasi_id' => $request->lokasi_id,
            'organizer_id' => $request->organizer_id,
            'deskripsi' => $request->deskripsi,
            'harga' => $request->harga,
    	]);
        
    	return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $event = Event::find($id);
        $idlokasi= $event->value('lokasi_id');
        $idkategori= $event->value('kategori_id');
        $idorg= $event->value('organizer_id');
        
        $iduser= Auth::user()->id;
        $user= User::all();
        // dd($idprof);
        // $idprof= Profile::select('id')->where("user_id",$iduser)->value('id');
        
        $lokasi= Lokasi::where('id',$idlokasi)->first();
        // dd($idorg);
        $org = Organizer::where('id',$idorg)->first();
        $kategori = Kategori::where('id',$idkategori)->first();
        // dd($idkategori);
        $hitungkomentar = Komentar::where('event_id',$id)->count();
        $komentar = Komentar::where('event_id',$id)->get();
        // dd($komentar);
        
        return view('Event.show', compact('event','kategori','lokasi','org','komentar','user'));
        
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $event = Event::find($id);
        $iduser= Auth::user()->id;
        // dd($idprof);
        $idprof= Profile::select('id')->where("user_id",$iduser)->value('id');
        $idorg = Organizer::where('profile_id',$idprof)->first();
        $lokasi= DB::table('lokasi')->get();
        // dd($idorg);
    
        $kategori = DB::table('kategori')->get();
        return view('event.edit',compact("lokasi","idorg","kategori","event"));

      
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
    		'nama' => 'required',
    		'waktu' => 'required',
            'lokasi' =>  'required',
            'kategori_id' => 'required',
            'lokasi_id' => 'required',
            'organizer_id' => 'required',
            'harga' => 'required',
            'deskripsi' => 'required',
    	]);
        $event = Event::findorfail($id);
        $data=[
            'nama' => $request->nama,
    		'waktu' => $request->waktu,
            'lokasi' => $request->lokasi,
            'kategori_id' => $request->kategori_id,
            'lokasi_id' => $request->lokasi_id,
            'organizer_id' => $request->organizer_id,
            'deskripsi' => $request->deskripsi,
            'harga' => $request->harga,
        ];
        $event->update($data);
        return redirect('/Event');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $event = Event::findorfail($id);
        $event->delete();
    
        return redirect('/Event');
    }
}

resources/views/event/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Add Event</title>

    <!-- Icons font CSS-->
    <link href="{{asset('colorlib/vendor/mdi-font/css/material-design-iconic-font.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('colorlib/vendor/font-awesome-4.7/css/font-awesome.min.css')}}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{{asset('colorlib/vendor/select2/select2.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('colorlib/vendor/datepicker/daterangepicker.css')}}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{{asset('colorlib/css/main.css')}}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <div class="p-t-15">
                        <a href="{{ route('Event.index') }}" ><button type="button" class="btn btn--blue my-4"> ke halaman depan </button></a>
                    </div>
                    <h2 class="title">Event Form</h2>
                    
                    <form method="POST" action="{{ route('Event.store') }}" enctype="multipart/form-data">
                        @csrf
                        
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Nama</label>
                                    <input class="input--style-4" type="text" name="nama">
                                </div>
                            </div>
                            @error('nama')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Tanggal(Format DDMMYYYY)</label>
                                    <input class="input--style-4" type="datetime" name="waktu" placeholder="DD-MM-YYYY">
                                </div>
                            </div>
                        </div>
                        @error('waktu')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        
                            
                        <div class="input-group">
                
                            <input  class="input--style-4" type="hidden" readonly="readonly" value="{{$idorg->id}}" name="organizer_id">
                        </div>
                        @error('organizer_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror    
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Kota</label>
                                    <div class="rs-select2 js-select-simple select--no-search">
                                        <select name="lokasi_id">
                                            <option disabled="disabled" selected="selected">Choose option</option>
                                            @foreach($lokasi as $item)
                                            <option value="{{$item->id}}" > {{$item->kota}}</option>
                                            @endforeach
                                        </select>
                                        <div class="select-dropdown"></div>
                                    </div>
                                </div>
                            </div>
                            @error('lokasi_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror 
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Lokasi</label>
                                    <input class="input--style-4" type="text" name="lokasi" placeholder="Tuliskan nama gedung">
                                </div>
                            </div> 
                            @error('lokasi')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span> 
                            @enderror
                          
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Kategori</label>
                                    <div class="rs-select2 js-select-simple select--no-search">
                                        <select name="kategori_id">
                                            <option disabled="disabled" selected="selected">Choose option</option>
                                            @foreach($kategori as $item)
                                            <option value="{{$item->id}}" > {{$item->nama}}</option>
                                            @endforeach
                                        </select>
                                        <div class="select-dropdown"></div>
                                    </div>
                                </div>
                            </div>
                            @error('kategori_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror 
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Harga</label>
                                    <input class="input--style-4" type="number" name="harga">
                                </div>
                            </div>
                            @error('harga')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror 
                            
                        </div>
                        <div class="input-group">
                            <label class="label">Deskripsi Acara</label>
                            <input class="input--style-4" type="text" name="deskripsi">
                        </div>
                        @error('deskripsi')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror 
                        <br>
                        <div class="p-t-15">
                            <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
        
    <!-- Jquery JS-->
    <script src="{{asset('colorlib/vendor/jquery/jquery.min.js')}}"></script> 
    <script src="{{asset('colorlib/vendor/jquery/jquery.min.js')}}"></script>
    <!-- Vendor JS-->
    <script src="{{asset('colorlib/vendor/select2/select2.min.js')}}"></script>
    <script src="{{asset('colorlib/vendor/datepicker/moment.min.js')}}"></script>
    <script src="{{asset('colorlib/vendor/datepicker/daterangepicker.js')}}"></script>

    <!-- Main JS-->
    <script src="{{asset('colorlib/js/global.js')}}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

resources/views/event/index.blade.php
@extends('listco.master')

@section('content')
<div class="slider-area hero-bg2 hero-overly">
        <div class="single-slider hero-overly  slider-height2 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-10 col-lg-10">
                        <!-- Hero Caption -->
                        <div class="hero__caption hero__caption2 pt-200">
                            <h1>Explore what you are finding</h1>
                        </div>
                        <!--Hero form -->
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
   


  <!-- listing Area Start -->
  <div class="listing-area pt-120 pb-120">
    <div class="container">
                <!--? Popular Directory Start -->
                <div class="popular-directorya-area fix">
                
                        <div class="row">
                            @forelse($event as $item)
                            <div class="col-lg-6">
                                <!-- Single -->
                                <div class="properties properties2 mb-30">
                                    <div class="properties__card">
                                        
                                        <div class="properties__caption">
                                            <h3><a href='Event/{{$item->id}}'>{{$item->nama}}</a></h3>
                                            <p>{{$item->deskripsi}}</p>
                                        </div>
                                        <div class="properties__footer d-flex justify-content-between align-items-center">
                                            <div class="restaurant-name">
                                                <img src="assets/img/gallery/restaurant-icon.png" alt="">
                                                <h3>Rp{{$item->harga}}</h3><br>
                                                <a class="btn btn-primary my-2" href="Event/{{$item->id}}/edit" role="button">Edit</a>
                                                <form action="/Event/{{$item->id}}" method='post'>
                                                    @csrf
                                                    @method("DELETE")
                                                    <input type="submit" value="delete" class="btn btn-danger my-2">
                                                </form>
                                                
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                            @empty
                            <h1 class="text-center">There is no data</h1>
                            @endforelse
                        </div>
                        
                </div>
                <!--? Popular Directory End -->
                <!--Pagination Start  -->
                
            </div>
        </div>
@endsection

resources/views/event/show.blade.php
@extends('listco.master')

@section('content')
<!--? Hero Start -->
<div class="slider-area2">
         <div class="slider-height3  hero-overly hero-bg4 d-flex align-items-center">
               <div class="container">
                  <div class="row">
                     <div class="col-xl-12">
                           <div class="hero-cap2 pt-20 text-center">
                              <h2>Blog Details</h2>
                           </div>
                     </div>
                  </div>
               </div>
         </div>
      </div>
      <!-- Hero End -->
<!--? Blog Area Start -->
<section class="blog_area single-post-area section-padding">
         <div class="container">
            <div class="row">
               <div class="col-lg-12 posts-list">
                  <div class="single-post">
                     <div class="feature-img">
                        <img class="img-fluid" src="{{asset('listco/assets/img/blog/single_blog_1.png')}}" alt="">
                     </div>
                     <div class="blog_details">
                        <h2 style="color: #2d2d2d;">
                        {{$event->nama}}<br>
                        
                        </h2>
                        <ul class="blog-info-link mt-3 mb-4">
                           <li><a href="#"><i class="fa fa-user"></i> {{$org->nama}}</a></li>
                       
                        </ul>
                        
                        <p>
                           Tanggal  : {{$event->waktu}}<br>
                           Lokasi   : {{$event->lokasi}}, {{$lokasi->kota}}<br>
                           Kategori : {{$kategori->nama}}<br>
                           Harga    : {{$event->harga}}<br>
                           Deskripsi: {{$event->deskripsi}}<br>

                        </p>
                        
                        
                     </div>
                  </div>
                 
                  
                  <div class="comments-area">
                     <div class="form-group">
                        <a class="btn btn-primary" href="{{ route('Event.index') }}" role="button">Kembali ke halaman depan</a>
                     </div>   
                     <h3 class="text-left my-3">Comments:</h3>
                        @forelse($user as $item=>$val)
                           @foreach($val->komentar as $item)
                           <div class="comment-list">
                              <div class="single-comment justify-content-between d-flex">
                                 <div class="user justify-content-between d-flex">
                                    <div class="thumb">
                                       <img src="{{asset('listco/assets/img/blog/comment_1.png')}}" alt="">
                                    </div>
                                    <div class="desc">
                                       
                                       
                                       <p class="comment"> 
                                          {{$item->komentar}}  <br>
                                                              
                                       </p>
                                       <div class="d-flex justify-content-between">
                                          <div class="d-flex flex-column">
                                             <div class="d-flex align-items-center">
                                                <h5 class="badge badge-primary" >
                                                   {{$val->name}}
                                                </h5>                                             
                                             </div>
                                             <br>
                                             
                                             <div class="d-flex flex-row">
                                                <div class="p-2">
                                                   <form action="/Komentar/{{$item->id}}" method='post'>
                                                      @csrf
                                                      @method("DELETE")
                                                      <input type="submit" value="delete comment" class="btn btn-outline-primary btn-sm">
                                                   </form>
                                                </div>
                                                
                                             </div>
                                             
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           @endforeach
                        @empty
                           <h2 class="text-center">No one comment</h2>

                        @endforelse                           
                        
                        
                     
                  </div>
                  @auth
                  <div class="comment-form">
                     <h4>Leave a Reply</h4>
                     <form class="form-contact comment_form" method="post" action="{{ route('Komentar.store') }}" id="commentForm">
                        @csrf
                        <div class="row">
                           <div class="col-12">
                              <div class="form-group">
                                 <textarea class="form-control w-100" name="komentar" id="comment" cols="30" rows="9"
                                    placeholder="Write Comment"></textarea>
                              </div>
                           </div>
                           <div class="col-sm-3">
                              <div class="form-group">
                                 <input class="form-control" name="user_id" id="name" type="text" readonly='readonly' value="{{Auth::user()->name}}" placeholder="Name">
                              </div>
                              <div class="form-group">
                                 <input class="form-control" name="event_id" id="name" type="hidden" readonly='readonly' value="{{$event->id}}" placeholder="Name">
                              </div>
                              
                           </div>
                           
                           
                        </div>
                        <div class="form-group">
                           <button type="submit" class="button button-contactForm btn_1 boxed-btn">Post Comment</button>
                        </div>
                     </form>
                  </div>
                  @endauth
                  @guest
                  <h2 class="text-center">Please login to comment</h2>
                  @endguest
               </div>
               
            </div>
         </div>
      </section>
@endsection